#
# SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: MIT
#

name: "tflite_model"
backend: "armnn_tflite"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 1, 244, 244, 3 ]
  }
]
output [
  {
    name: "MobilenetV1/Predictions/Reshape_1"
    data_type: TYPE_FP32
    dims: [ 1, 1001 ]
  }
  
]
optimization { execution_accelerators {
  cpu_execution_accelerator : [ { 
    name : "armnn" 
    parameters { key: "num_threads" value: "2" }
    parameters { key: "reduce_fp32_to_fp16" value: "on"}
    parameters { key: "fast_math_enabled" value: "on" }

  } ]
}}

